### ISSUE TITLE
Sensors for Gelbe Tonne, Schwarze Restmülltonne & Blaue Papiertonne are not available

### ISSUE THREAD

**Issue by MikeDeltaHH** [custom-components/sensor.stadtreinigung_hamburg#16]
## Version of the custom_component
v1.1.1

## Logs

stadtreinigung_hamburg: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await coro
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/stadtreinigung_hamburg/sensor.py", line 125, in update
    collections = sorted(self.data.data, key=lambda x: x.date)
AttributeError: 'StadtreinigungHamburgData' object has no attribute 'data'

```

## Describe the bug

Hi!

The sensors for three of the four garbage cans are displayed as unavailable, think since yesterday or so - the sensor for the bio garbage can is available but only the last emptying 20 hours ago is displayed.

**Comment by gordenfalk** [comment]
Same here

**Comment by vigonotion** [comment]
try version `v1.1.2`
